default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_development
  username: kayro
  password: ek12k13

test:
  <<: *default
  database: blog_api_test
  username: kayro
  password: ek12k13

production:
  <<: *default
  database: auth_api_blog
  username: auth_api_blog
  password: <%= ENV['AUTH_API_BLOG_DATABASE_PASSWORD'] %>
